# Shell
set-option -g default-shell /bin/fish

# Navigation
set-window-option -g mode-keys vi

set -g base-index 1
set -g detach-on-destroy off
set -g escape-time 0
set -g history-limit 1000000
set -g focus-events on
set -g renumber-windows on
set -g status-interval 3
bind-key x kill-pane

# Pane resizing
bind -r S-Left resize-pane -L 5
bind -r S-Down resize-pane -D 5
bind -r S-Up resize-pane -U 5
bind -r S-Right resize-pane -R 5
bind -r m resize-pane -Z

# Prefix
set -g prefix C-a
bind C-a send-prefix

# Terminal / colors
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"
set -as terminal-features ',*:RGB'
set -g allow-passthrough on

# Clipboard
set -s copy-command 'wl-copy'

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'wl-copy'

# Reload
unbind r
bind r source-file ~/.tmux.conf \; display-message "Config reloaded"

# Status line
set-option -g status-position top
bind u set -g status

set -g mode-style "fg=black,bg=#fafafa"
set -g message-style "fg=#fafafa,bg=#18181b"
set -g message-command-style "fg=#fafafa,bg=#18181b"
set -g pane-border-style "fg=#27272a"
set -g pane-active-border-style "fg=#fafafa"
set -g status "on"
set -g status-interval 1
set -g status-justify "centre"
set -g status-style "fg=#fafafa"
#set -g status-bg "#202023"
set -g status-left-length "100"
set -g status-right-length "100"
set -g status-left-style NONE
set -g status-right-style NONE
set -g status-left "#[fg=#fafafa,bold]#S#[fg=#72727b]:#[fg=#71717a]#(tmux list-sessions | wc -l)  "
set -g status-right "#[fg=#72727b]%H:%M"
setw -g window-status-activity-style "underscore,fg=white,bg=#09090b"
setw -g window-status-separator "  "
setw -g window-status-style "NONE,fg=#52525b"
setw -g window-status-format '#[fg=#71717a]#I#[fg=#52525b]:#W'
setw -g window-status-current-format '#[fg=white,bold]#I#[fg=white,bold]:#W'

# TPM
run '~/.tmux/plugins/tpm/tpm'
