# -----------------------------
# Plugins (TPM)
# -----------------------------
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'janoamaral/tokyo-night-tmux'

# -----------------------------
# Tema Tokyo Night
# -----------------------------
set -g @tokyo-night-tmux_theme moon
set -g @tokyo-night-tmux_show_git 1
set -g @tokyo-night-tmux_show_wbg 0 
set -g @tokyo-night-tmux_show_netspeed 0
set -g @tokyo-night-tmux_show_battery_widget 0
set -g @tokyo-night-tmux_show_music 0
set -g @tokyo-night-tmux_show_path 1
set -g @tokyo-night-tmux_show_hostname 1
# -----------------------------
# Shell padrão
# -----------------------------
set-option -g default-shell /bin/fish

# -----------------------------
# Navegação / comportamento
# -----------------------------
set-window-option -g mode-keys vi
set -g base-index 1
set-option -g status-position top

# -----------------------------
# Prefixo
# -----------------------------
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# -----------------------------
# Terminal / Cores
# -----------------------------
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"
set -as terminal-features ',*:RGB'
set -g allow-passthrough on

# -----------------------------
# Clipboard Wayland
# -----------------------------
set -s copy-command 'wl-copy'

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'wl-copy'

# -----------------------------
# Reload da config
# -----------------------------
bind r source-file ~/.tmux.conf \; display-message "Config reloaded"

# -----------------------------
# TPM (sempre no final)
# -----------------------------
run '~/.tmux/plugins/tpm/tpm'
